---
domain: Samples
appId: luego-starter-app
groupId: io.provingly
appVersion: 1.0.0

provider:
  name: Provingly
  email: info@provingly.io

generateOpenApi: true
dependencies: []

localizedInfo:
  - label: Luego Starter App
    description: A sample to quickstart your development of Luego apps
    tags: [ 'sample', 'starter' ]
    lang: en
    country:
